image: golang:1.12

stages:
  - all
  - build-docker

before_script:
  # Packages
  - PACKAGES="openssh-client git bash"
  - command -v apt >/dev/null 2>&1 && (apt-get update && apt-get install -y ${PACKAGES}) || (apk update && apk add ${PACKAGES})

  # https://docs.gitlab.com/ee/ci/ssh_keys/
  - echo "Configuring git"
  - eval $(ssh-agent -s)
  - echo "$SSH_CI_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && chmod 600 ~/.ssh
  - echo "gitlab.com,35.231.145.151 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=" >> ~/.ssh/known_hosts

  # Force use of ssh urls instead of https for gitlab.com. Has to be done before any go get...
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"

all:
  stage: all
  cache:
    paths:
      - .cache
  script:
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH="${PATH}:${GOPATH}/bin"
    # Install global go tools
    - go install golang.org/x/lint/golint
    - go get github.com/jstemmer/go-junit-report
    # Run lint and tests
    - golint -set_exit_status ./...
    # Timeout need at least 30s when testing with C2AETEST_POSTGRES=1 to let it time to drop / create the schema between tests.
    - go test -v -coverprofile=cover.out -timeout 30s -race ./... | tee >(go-junit-report > report.xml)
    - cat cover.out | grep -v "_mocks.go" > cover_filtered.out
    - go tool cover -func cover_filtered.out
    - ./scripts/build.sh
  coverage: '/^total:\t+\(statements\)\t+(\d+\.\d+)%/'
  artifacts:
    reports:
      junit:
        - report.xml
    paths:
      - bin/*
    expire_in: 1 week

build-docker:
  image: docker:stable
  stage: build-docker
  tags:
    - docker
  services:
    - docker:dind
  dependencies:
    - all
  script:
    - ./scripts/docker-build.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/teserakt/c2ae/api:${CI_COMMIT_REF_NAME//\//_}
    - docker push registry.gitlab.com/teserakt/c2ae/api:${CI_COMMIT_SHORT_SHA}
    - docker push registry.gitlab.com/teserakt/c2ae/cli:${CI_COMMIT_REF_NAME//\//_}
    - docker push registry.gitlab.com/teserakt/c2ae/cli:${CI_COMMIT_SHORT_SHA}
