version: '3.7'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
