// Copyright 2020 Teserakt AG
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/teserakt-io/automation-engine/internal/engine/actions (interfaces: ActionFactory,Action)

// Package actions is a generated GoMock package.
package actions

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "github.com/teserakt-io/automation-engine/internal/models"
	reflect "reflect"
)

// MockActionFactory is a mock of ActionFactory interface
type MockActionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockActionFactoryMockRecorder
}

// MockActionFactoryMockRecorder is the mock recorder for MockActionFactory
type MockActionFactoryMockRecorder struct {
	mock *MockActionFactory
}

// NewMockActionFactory creates a new mock instance
func NewMockActionFactory(ctrl *gomock.Controller) *MockActionFactory {
	mock := &MockActionFactory{ctrl: ctrl}
	mock.recorder = &MockActionFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockActionFactory) EXPECT() *MockActionFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockActionFactory) Create(arg0 models.Rule) (Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockActionFactoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActionFactory)(nil).Create), arg0)
}

// MockAction is a mock of Action interface
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
}

// MockActionMockRecorder is the mock recorder for MockAction
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockAction) Execute(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Execute", arg0)
}

// Execute indicates an expected call of Execute
func (mr *MockActionMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAction)(nil).Execute), arg0)
}
